### ISSUE TITLE
Heat map name should have leading spaces removed (like GUI builder) or stop build and report error if name starts with space.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#10]
Entering just a space for a heat map or starting the name with a space causes a heat map to be created that will fail in the viewer.

**Comment by jma7** [comment]
Leading spaces and trailing spaces are removed from heat map name, output name, covariate name and description.

**Comment by jmelott** [comment]
Still fails if user enters only a single space for the heat map name.
Heat map is created, but extra files show up in output directory and error in stderr.txt as follows: 
find: paths must precede expression: `rm'

**Comment by jma7** [comment]
If the input field is empty, user will get error message in stderr. Please check again in your setting.
