### ISSUE TITLE
Builder Version Mismatch

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#2]
Builder version of GenePattern_NGCHM_BasicBuilder says it is version 5 on the GenePattern screen, but  when viewing map, the map says it was built with Galaxy 2.9.1.   Build version should match correct software.

**Comment by jmelott** [comment]
Issue still present 4/2/2020

**Comment by jma7** [comment]
This could be discussed in NGCHM meeting. Not sure if needed.

**Comment by jma7** [comment]
The builder version has been updated, the changes are in GalaxyMapGen.jar, now it shows "GenePattern 2.10.1"
