### ISSUE TITLE
Filtering and/or reporting of invalid heat map names and descriptions needed.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#4]
Jobs fail when invalid characters put into name field and possibly description field.  
I believe the current galaxy implementation will replace invalid characters with spaces in some cases.

Suggest testing for bad characters and reporting them or replacing them with other characters rather than sending them onto GalaxyMapGen.  (I'd question if this should even be named GalaxyMapGen)

To reproduce issue:
Copy contents of attached file to name and description fields in builder.
[input_test_characters.txt](https://github.com/MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder/files/4300259/input_test_characters.txt)

**Comment by jmelott** [comment]
Issue still exists 4/2/2020

**Comment by jma7** [comment]
Right now I only filter for slash because of the security issue. I will update script to filter for other characters.

**Comment by jma7** [comment]
Added a function to check for non-alphanumeric characters as in GUI builder. Heat Map Name and Output Name cannot contain non-alphanumeric characters (Exceptions: space, hyphen, and underscore)

**Comment by jmelott** [comment]
Partially fixed.  Description field still not filtered properly.  Will close this and open new bug just for description field error message.
