### ISSUE TITLE
Improve error output when user submits large matrices to indicate that they are not allowed.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#6]
Currently, system states the following if a attempts to use a large matrix (greater than 10,000 for sum of rows and columns) to create a heatmap.
If the sum of number of rows and number of columns greater than 10000, it might exceed the memory limit in R dist calculation. [1] "euclidean"

The message should be changed to state that the system does not support matrices where the sum of the number of rows and columns is greater than 10,000.

**Comment by jma7** [comment]
According the discussion in NGCHM meeting, it should allow matrix greater than 10,000, the adjustment will be on the server side by the administrator. I will update warning message to make this more clear.
https://www.genepattern.org/administrators-guide

**Comment by jma7** [comment]
The warning message has been added.

**Comment by ChrisWakefield** [comment]
@jma7 
> According the discussion in NGCHM meeting, it should allow matrix greater than 10,000, the adjustment will be on the server side by the administrator. I will update warning message to make this more clear.

But how is this configured on the server side?  Where can we put the limiting parameters?

**Comment by jma7** [comment]
Right now the error message shows:
"If the sum of number of rows and number of columns greater than 10000, it might exceed the memory limit in R dist calculation. Please adjust the --max-mem-size flag in R options in Programming Language Options at the GenePattern Server side if you need more memory in R. Check detail at https://www.genepattern.org/administrators-guide."

**Comment by jmelott** [comment]
How big of a matrix would we expect our current GenePattern server to be able to handle with its current configuration?
What do we expect to happen with the GenePattern Builder module if someone enters a map that is greater than the configured memory options would permit?  Should this cause the job to fail, GenePattern to stop responding, Gene Pattern to crash, or the whole Docker Container or server to go down?

**Comment by jma7** [comment]
I get into the docker container which runs the builder, it seems the dist calculation on large matrix is killed by kernel without any error message other than "killed". When I run the same dist calculation on desktop I get "vector memory exhausted" message from R.  When I run this calculation on laptop, there is no error message but the memory consumption freeze the laptop. 
According to the GenePattern documentation, there is option to increase the memory limit for modules
https://www.genepattern.org/administrators-guide#increasing-memory-allocation
I don't observe exceeding memory limit crashes the docker container or whole server. So I think it is safe to say

> "If the sum of number of rows and number of columns is greater than 10000, the R dist calculation will use large amount of memory which could cause job to fail. To increase memory allocation, please check https://www.genepattern.org/administrators-guide#increasing-memory-allocation and https://www.genepattern.org/administrators-guide#_Programming_Languages ."

**Comment by jmelott** [comment]
The message currently says:

If the sum of number of rows and number of columns greater than 10000, it might exceed the memory limit in R dist calculation. Please adjust the --max-mem-size flag in R options in Programming Language Options at the GenePattern Server side if you need more memory in R. Check detail at https://www.genepattern.org/administrators-guide.

This is different from the last message stated above.
If that was the final text decided on for this issue, then it can be closed.

**Comment by jma7** [comment]
The message has been updated to:

> If the dimension of your matrix is large in one direction or both directions, the job might fail due to server capacity. To increase memory allocation, please see https://www.genepattern.org/administrators-guide#increasing-memory-allocation and https://www.genepattern.org/administrators-guide#_Programming_Languages .

The docker image has been updated.
