### ISSUE TITLE
Description field in builder needs test for invalid characters and/or improved error message.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#7]
The description field is not checking for invalid characters that can cause the job to fail.  It should follow the similar rules to what the GUI builder has and report what characters are allowed to the user if they enter invalid ones.

Current error message with failure is as follows:
run hclust
FATAL ERROR: GalaxyMapGen could not parse JSON arguments: {"build_platform": "GenePattern", "chm_name":"ABCDEFGHIJKLMNOPQRSTUVWXYZ", "chm_description":"♂", "!"#$%&'()*+,-./0123456789:;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{":"}~⌂ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼", "output_location":"bad_char.ngchm", "existing_atr":"path", "existing_gtr":"path","matrix_files": [  {"path":"/opt/genepattern/users/jmmelott@mdanderson.org/uploads/tmp/run7055271697091648798.tmp/Input.Filename/1/matrix_03_10_10_genes_genes.tsv","name":"datalayer","summary_method":"average"}],"row_configuration": {"order_file": "/home//2004161437/ROfile.txt","dendro_file": "/home//2004161437/RDfile.txt","order_method":"Hierarchical","distance_metric":" euclidean","agglomeration_method":"ward.D","data_type":["labels"]},"col_configuration": {"order_file": "/home//2004161437/COfile.txt","dendro_file": "/home//2004161437/CDfile.txt","order_method":"Hierarchical","distance_metric":"euclidean","agglomeration_method":"ward.D","data_type":["labels"]},"classification_files": [ ]}
gp_job_101

**Comment by jmelott** [comment]
Specifically there are problems with quote characters causing the failure.
Description of '"test"' will cause the same failure.
Other characters that interfere with JSON representation may cause issues as well.

**Comment by jma7** [comment]
The GUI builder heat map description has following filter:
Heat Map Description cannot contain non-alphanumeric characters (Exceptions: space, hyphen, and underscore)
I will follow their rule as well.
