### ISSUE TITLE
Heat map name should be limited in length. 

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/GenePattern_NGCHM_BasicBuilder#9]
For consistency with the GUI builder, we should probably stick with 14 character max length for the heat map names.
Greater than 255 character names cause the build to fail due to maximum file name limits in both Unix and Windows.   In the case of the heat map name, the thumbnail image creation fails, but the heat map is created.

**Comment by jma7** [comment]
Just wonder if we could increase the max length to less than 256? Since right now, the default heatmap name and output name is the base name for uploaded matrix, which could be easily longer than 14 characters. The GenePattern team asked for setting up default name this way and I think this is quite convenient for the user.

**Comment by jmelott** [comment]
It probably could be longer.  How much is up in the air a bit as it all gets complicated. 
Mark Stucky might know a reason they stopped at 14 in particular.  In the GUI Builder they don't ask for separate entries, both are driven from the Map name.

There could also be some issues as to how long of a name they want to display in places where they list the map names like the collection tools Bradley put together.  I remember really messing up the screens on that application when I tested it and and used extremely long map names.  You might want to check with Bradley too and see if that fed into the decision for using 14 characters

The map name is displayed at the top of the viewer, so if you make it too long it can either take up too much space or need to be cut off.  It looked to me like that was the main limitation there.   Just from recent testing, without looking at the code, it looked to me like the map name was being used to generate the directory name the map was stored in in some cases, but in other cases it was a hash id code if the name was long.  I haven't checked, but there might be specific comments in the code about that.

Unix path sections and filenames are limited to 256 bytes each.  If someone ends up using unicode characters in file names (although you may be restricting that so that it can't happen with the other filters) then those could possibly limit each path element or filename to 63 characters as unicode characters can take up 4 bytes each.  Just from that it might be best to not go over 63 characters if the could possibly use a unicode name.

For windows, in addition to the maximum file name length of 256, there's a maximum path length (full path + file name) on some systems. People seem to disagree exactly what the limit is, but possibly as low as 259 characters.  
See https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista

So, that would possibly limit the total of the path up to where you store the heatmaps + the heatmap name (or hash length)  used as a directory + the slashes + the output filename to 259.
If you don't want to do some extra math of the sum of the path and file components, it might be best to keep them somewhat smaller, although possibly much bigger than 14.

And then don't forget that .ngchm is part of your file name.

Let me know what you decide.

**Comment by jma7** [comment]
I just checked GUI builder, it seems the heat map name limit is 40 characters. I will be fine with using 40 as max length for heat map name and output file name.
